src/components/Footer.jsx
src/pages/_app.js

fixed #2 
- i made the footer component. Check if it looks good to you

#2 Created footer and made it responsive

---

src/components/Pagination.jsx
src/components/RecipeCard.jsx
src/pages/index.js
src/styles/globals.css

fixed #10 and #13
- created the recipe card component
- created pagination component
- hide pagination when there is 1 page
pagination:

#10 recipe card and #13 pagination

---

src/components/RecipeTag.jsx
src/pages/index.js

#9 recipe tags

---

src/components/RecipeCard.jsx
src/pages/explore.jsx

fixed #5 
- made the filter and result sections of the explore page
- made the explore page responsive
- made the recipe card responsive

#5 explore page

---

src/components/Review.jsx
src/pages/index.js

#8 review component

---

src/components/Pagination.jsx
src/components/Review.jsx
src/pages/recipe/[slug].jsx

fixed #4 
you'll need to use the component in the review section

#4 recipe page

---

src/components/Carousel.jsx
src/components/RecipeCard.jsx
src/pages/explore.jsx
src/pages/index.js

- fixed #14 
- modified the recipe card size depending on the screen size
- modified the number of recipe cards displayed in the result section of the explore page depending on the screen size

#14 carousel

---

src/components/Carousel.jsx
src/components/RecipeCard.jsx
src/pages/index.js

fixed #3 and made it responsive

#3 Home page

---

src/components/Carousel.jsx
src/components/FAQDropdown.jsx
src/pages/index.js

#11 FAQ Component

---

src/components/FAQDropdown.jsx
src/components/Navbar.jsx
src/pages/contact.jsx

- fixed #7 and made it responsive
- changed "class" attribute to "className" attribute in html icon element to resolve error in Navbar and FAQDropDown

#7 Contact us page

---

src/components/RecipeCard.jsx
src/pages/explore.jsx

23 changes explore page

---

src/components/Navbar.jsx
src/pages/login.jsx
src/pages/signup.jsx

31 login & signup page

---

src/components/IngrStep.jsx
src/pages/index.js

40 ingredient & step row component

---

src/pages/account/[slug].jsx

39 create side/top navbar in user account page

---

src/pages/create-recipe.jsx

36 step 1 of create recipe page

---

src/pages/create-recipe.jsx

- fixed #38 
- redirect to home page when pressed submit button
- add alert message for successfully creating a recipe

38 step 3 of create recipe page

---

src/pages/404.jsx
src/pages/account/[slug].jsx

32 profile section of user account page

---

src/pages/account/[slug].jsx
src/pages/explore.jsx

33 favourite and your created recipes sections of user account page

---

src/components/Pagination.jsx
src/pages/account/[slug].jsx
src/pages/explore.jsx
src/pages/recipe/[slug].jsx

- fixed #34 
- changed the colours of pagination component

34 review section of user account page

---

src/pages/account/[slug].jsx

35 setting section of user account page
